[auth]
enabled = true
enable_signup = true
enable_anonymous_sign_ins = true

[functions.generate-gemini-content]
verify_jwt = false

[functions.app-version-config]
verify_jwt = false

[functions.delete-account]
verify_jwt = false
